project:
  type: book
  output-dir: docs

execute:
  freeze: auto
  
book:
  title: "Predicting Loan Defaults"
  favicon: assets/img/logo.png
  output-file: "users-guide"
  reader-mode: true
  public-url: https://zadchin.github.io/CS50Section/
  repo-url: https://github.com/zadchin/CS50Section
  repo-actions: [issue]
  chapters:
    - index.qmd
    - 01_Section_1.qmd
    - 02_Section_2.qmd
    - 02_5_Section_2.qmd
    - 03_Section_3.qmd
    - 04_Section_4.qmd
    - 05_Section_5.qmd
    - 06_Section_6.qmd
    - 07_Section_7.qmd
    - part: 08_Section_8.qmd
      chapters:
        - testing/test1.qmd
        - testing/test2.qmd

include-after-body:
  text: <script type="text/javascript" src="page-nav-foot.js"></script>

bibliography: references.bib

format:
  html:
    code-block-border-left: true
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: style.css
    
    include-before-body:
      - _dollars.tex
      - _bold_html.tex
      - _macros.tex
      - _dollars.tex
        